package heuristics

import (
	"strings"

	"github.com/konsbe/trading-agent/services/data-analyzer/internal/compute"
)

// Actions the liquidity-sweep rule can return.
const (
	ActionWatch     = "WATCH"
	ActionBuyWatch  = "BUY_WATCH"
	ActionTrimWatch = "TRIM_WATCH"
)

// BotVIXThresholds are the bands the analyst-bot actions engine hardcodes
// (services/analyst-bot/actions/engine.py): >35 extreme_fear, >20 elevated,
// <12 complacency, else normal. They are not read from TECHNICAL_VIX_*.
var BotVIXThresholds = compute.VIXThresholds{Fear: 35, Elevated: 20, Complacency: 12}

// SweepRuleInput is what services/analyst-bot/actions/rules/liquidity_sweep.py
// reads, in the shape it sees after Python's `or` defaults. A nil pointer is a
// missing / None key.
type SweepRuleInput struct {
	Kind       string   // last_sweep.kind, "" when last_sweep is null/missing
	BarClose   *float64 // last_sweep.bar_close
	SweptLevel *float64 // last_sweep.swept_level
	BullishOB  bool     // bool(payload["last_bullish_ob"])
	BearishOB  bool     // bool(payload["last_bearish_ob"])
	TrendDir   string   // trend payload direction, "" when missing
	VIXRegime  string   // macro vix_regime, "" when no VIX
}

// SweepRuleResult is the rule's (action, confluence); the reasons text is not
// ported.
type SweepRuleResult struct {
	Action     string
	Confluence int
}

// EvaluateSweepRule is a line-for-line port of liquidity_sweep.evaluate as it
// runs today. Keep it that way: the H9/H10 replay tests the live rule, not an
// idealised one. Parity is pinned by testdata/sweep_rule_parity.json, which is
// generated by running the Python function.
func EvaluateSweepRule(in SweepRuleInput) SweepRuleResult {
	confluence := 1
	action := ActionWatch
	riskOff := in.VIXRegime == "elevated" || in.VIXRegime == "extreme_fear"

	switch {
	case strings.Contains(in.Kind, "low"):
		closedBackAbove := in.BarClose != nil && in.SweptLevel != nil && *in.BarClose > *in.SweptLevel
		if closedBackAbove {
			confluence++
			if in.BullishOB {
				confluence++
			}
			if in.TrendDir == "up" {
				confluence++
			}
			if in.TrendDir == "up" && !(riskOff && in.TrendDir != "up") {
				action = ActionBuyWatch
			} else if riskOff && in.TrendDir != "up" {
				action = ActionWatch
			} else {
				action = ActionBuyWatch
			}
		} else {
			action = ActionWatch
		}
	case strings.Contains(in.Kind, "high"):
		closedBackBelow := in.BarClose != nil && in.SweptLevel != nil && *in.BarClose < *in.SweptLevel
		if closedBackBelow {
			confluence++
			if in.BearishOB {
				confluence++
			}
			if in.TrendDir == "down" {
				confluence++
			}
			action = ActionTrimWatch
		} else {
			action = ActionWatch
		}
	default:
		action = ActionWatch
	}
	return SweepRuleResult{Action: action, Confluence: confluence}
}
