// Global type declarations for the trading-agent SPOG shell
import * as React from "react";

// SVG asset declarations
declare module '*.svg' {
  import React from 'react';
  const ReactComponent: React.FunctionComponent<React.SVGProps<SVGSVGElement>>;
  export { ReactComponent };
  const src: string;
  export default src;
}

// Image asset declarations
declare module '*.png' {
  const src: string;
  export default src;
}

declare module '*.jpg' {
  const src: string;
  export default src;
}

declare module '*.jpeg' {
  const src: string;
  export default src;
}

declare module '*.gif' {
  const src: string;
  export default src;
}

declare module '*.webp' {
  const content: string;
  export default content;
}

// Global window extensions
declare global {
  /**
 * Configuration types and loader for dynamic MFE loading
 * Matches the format generated by mfe-operator's config_json.go
 */

  interface BuildInfo {
    bannerString?: string;
    productRelease?: string;
    productBuild?: string;
    spogDomain?: string;
    keycloakUrl?: string;
    keycloakRealm?: string;
    keycloakClientId?: string;
    /** momentum-api base URL, read by mfe-scanner. */
    momentumApiUrl?: string;
  }

  interface MFEConfigEntry {
    label: string;
    version: string;
    endpoint: string;          // remoteEntry.js URL - required
    module: string;            // Exposed module name - required
    description?: string;
    roles?: string[];
    enabled: boolean | string; // Support both boolean and string
    isConfigMfe?: boolean;
    scope?: string;            // Override scope name (if different from key)
    nav_group?: string;        // Sidebar group label
    nav_order?: number;        // Group order (ascending); 0 pins the group to the sidebar bottom
    nav_sub_order?: number;    // Item order inside its group (ascending)
    nav_icon?: string;         // Icon name, e.g. "mdi-chart-box-outline"
    router_path?: string;      // Route URL, e.g. "/candidates"
  }

  interface MFEConfigEntryWithRoles extends Omit<MFEConfigEntry, 'roles'> {
    roles: string[];           // Guaranteed to be an array
  }

  interface ShellSpogDefinition extends Omit<MFEConfigEntry, 'endpoint' | 'module'> {
    mainJsUrl?: string;        // Only for shell
    endpoint?: string;         // Optional for shell
    module?: string;           // Optional for shell
    config?: BuildInfo & Record<string, unknown>;
  }


  interface AppConfig {
    shell_spog?: ShellSpogDefinition;  // Shell configuration
    mfes: Record<string, MFEConfigEntry>;  // MFE configurations
    /** Iframe-backed tools; optional */
    iframes?: Record<string, MFEConfigEntry>;
  }
  interface Window {
    __APP_CONFIG__?: AppConfig;
    RUNTIME_CONFIG?: Record<string, Record<string, string> | string>;

    // Bootstrap flag for backward compatibility
    __BOOTSTRAP_CALLED__?: boolean;

    // Dynamic MFE containers added at runtime by loadRemoteEntry
    // e.g., window['mfe_candidates']
    [key: string]: any;
  }

  // Webpack Module Federation API
  var __webpack_public_path__: string;
  var __webpack_init_sharing__: (scope: string) => Promise<void>;
  var __webpack_share_scopes__: { default: any };
}

// JSX support
declare namespace JSX {
  interface IntrinsicElements {
    [elemName: string]: any;
  }
}

export {};