server {
    listen 80;
    root /usr/share/nginx/html;

    location = /config.json {
        add_header Cache-Control "no-store";
    }

    location / {
        add_header Access-Control-Allow-Origin "*";
        try_files $uri /index.html;
    }
}
